### ISSUE TITLE
other lab

### ISSUE THREAD

**Issue by Fer60** [graasp/graasp-desktop#168] opened 2019-08-14 07:28 UTC

**Comment by Fer60** [comment] 2019-08-14 07:32
I wnat to use a PhET lab in French and have used the html link in GRAASP for this. Online this wotks well but it does not load in the desktop viewer.
By accident I discoverd that the tabel tool app does not load in the "view" mode, but when I then save it the table is loaded.

**Comment by juancarlosfarah** [comment] 2019-08-15 12:37
Hi @Fer60, can you let me know what lab this is?

**Comment by Fer60** [comment] 2019-08-15 13:32
Hi Juan Carlos,

This is the url: https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_fr.html

It is working in the onnline version, but not visible in the offline desktop viewer.



dr. Fer Coenders,
GO-GA, Department of Instructional Technology (IST)
Faculty BMS, University of Twente
https://www.golabz.eu<https://www.golabz.eu/>
https://www.utwente.nl/en/bms/ist/
Tel (+31) 053-4893081 )office); (+31) 0316-228920 (home)

**Comment by juancarlosfarah** [comment] 2019-08-15 15:05
Hi @Fer60, when you say that it's not working, do you mean that the lab is showing in English and not French?

I checked the space `7slvq0` and the language is in English. If you change it to French, it should work.

**Comment by Fer60** [comment] 2019-08-15 18:01
No the lab is not lead or does not appels at all.


Fer



dr. Fer Coenders
GO-GA, Department of Instructional Technology (IST)
Faculty BMS, University of Twente
https://www.golabz.eu/
https://www.utwente.nl/en/bms/ist/
Tel (+31) 053-4893081 (office)l (+31) 0316-228920 (home)

Op 15 aug. 2019 17:05 schreef Juan Carlos Farah <notifications@github.com>:

Hi @Fer60<https://github.com/Fer60>, when you say that it's not working, do you mean that the lab is showing in English and not French?

I checked the space 7slvq0 and the language is in English. If you change it to French, it should work.

**Comment by juancarlosfarah** [comment] 2019-08-15 19:13
I've been working with space `7slvq0` and the lab is working fine for me. It's in English, though.

How are you adding the French lab? What space is it on?

**Comment by Fer60** [comment] 2019-08-16 08:48
Hi Juan Carlos,

I have made you owner of the ILS on GRAASP of Construire un Atome. Online the French version of the lab is working perfectly, but when I load this into the desktop viewer the lab is missing. It does not seem to load.

And the same problem as in the English version of this ILS occurs: in the Investigation phase I included four elements: a document, the PhET lab, a Table Tool, and a document. This last document is not properly visible in the desktop viewer, only the last line is visible. You can check this for yourself when comparing the online and offline versions.

When I change the language in the desktop viewer from English to French it only changes the elements from the viewer, not the ILS nor the lab. So it changes Saved Spaces into Espaces Enregistres etc, but not the ILS nor the lab but also not the top row (File, edit, view, window, help).


As the Benin teachers really want to have everything in French I really hope you can solve the issue of importing the labs in French.

Cheers,

Fer



dr. Fer Coenders,
GO-GA, Department of Instructional Technology (IST)
Faculty BMS, University of Twente
https://www.golabz.eu<https://www.golabz.eu/>
https://www.utwente.nl/en/bms/ist/
Tel (+31) 053-4893081 )office); (+31) 0316-228920 (home)

**Comment by juancarlosfarah** [comment] 2019-08-16 13:47
Hi @Fer60. Thanks for sharing the learning space with me. There are a couple of issues here, but it's all on the setup side.

Firstly, changing the language on the desktop viewer indeed only changes the viewer interface. This is by design, as you might want to have different learning spaces with different languages. To change the language of a learning space, you need to change it in Graasp itself:

<img width="1345" alt="Screenshot 2019-08-16 at 15 36 54" src="https://user-images.githubusercontent.com/1707188/63171449-e3440500-c03b-11e9-849e-484f56b89788.png">

Once you have changed that to French, then all of the apps and labs, will know that they have to show their French version, if they have one. This leads us to the second problem. You have added the lab using a link.

<img width="607" alt="Screenshot 2019-08-16 at 15 37 52" src="https://user-images.githubusercontent.com/1707188/63171494-01116a00-c03c-11e9-8f31-aaaa6b0b48d2.png">

By default, we do not show links in the desktop viewer, as they would require an "online" connection to render properly. The way to add the app and have it render in French is simply by adding the app as normal, and then setting the language to French as indicated in the first screenshot. I have gone ahead and done that:

<img width="1327" alt="Screenshot 2019-08-16 at 15 43 04" src="https://user-images.githubusercontent.com/1707188/63171811-a4fb1580-c03c-11e9-8896-0a5ae48bc300.png">

Now, as seen below, the resources inside the learning space, specifically the table and the lab (as the input app doesn't have French yet), render in French, as shown below:

<img width="1570" alt="Screenshot 2019-08-16 at 15 45 37" src="https://user-images.githubusercontent.com/1707188/63171959-eb507480-c03c-11e9-8aff-1e58db5e9a13.png">

As per the issues with the document, you can see that it has been fixed in today's release [v0.12.0](https://github.com/graasp/graasp-desktop/releases/tag/v0.12.0), as shown in the screenshot.

Hope that helps!

**Comment by Fer60** [comment] 2019-08-18 12:39
Hi Juan Carlos,

So far all is working well. The lab is indeed in French and is scalable as is the table.
Thanks,



Fer



dr. Fer Coenders,
GO-GA, Department of Instructional Technology (IST)
Faculty BMS, University of Twente
https://www.golabz.eu<https://www.golabz.eu/>
https://www.utwente.nl/en/bms/ist/
Tel (+31) 053-4893081 )office); (+31) 0316-228920 (home)

**Comment by juancarlosfarah** [comment] 2019-08-18 14:58
Awesome! Glad it’s working.

**Closed by juancarlosfarah** 2019-08-18 14:58 UTC
Labels: question, wontfix
