### ISSUE TITLE
loading space causes EPERM exception error on rename

### ISSUE THREAD

**Issue by Fer60** [graasp/graasp-desktop#159] opened 2019-08-07 09:42 UTC
The load function in the viewer is not working. I had saved an ILS on a usb stick. Then deleted the ILS from the viewer and tried to load it again into the viewer from the stick, but it does not load. I waited four minutes but nothing happens (only the moving circles).

**Comment by juancarlosfarah** [comment] 2019-08-07 11:01
Thanks @Fer60 for reporting. I can see the error on Sentry (our exception reporting tool). It is the following:

```
Error: EPERM: operation not permitted, rename 'C:\Users\...\AppData\Roaming\graasp-desktop\var\tmp' -> 'C:\Users\...\AppData\Roaming\graasp-desktop\var\5d3f0cb5fd555f7e3fbe7ee2'
```

Looks like it is related to the following issue:

https://github.com/sindresorhus/electron-store/issues/31

Will investigate.

**Comment by juancarlosfarah** [comment] 2019-08-07 12:55
I was able to reproduce on Windows 10 inside a VirtualBox VM. Will work on a fix now.

**Comment by juancarlosfarah** [comment] 2019-08-07 18:07
Looks like this is a well known problem on Windows. `rimraf` uses this workaround to try and perform an action multiple times.

https://github.com/isaacs/rimraf/blob/79b933fb362b2c51bedfa448be848e1d7ed32d7e/rimraf.js#L338

Te accompanying comment reads:

```
  // We only end up here once we got ENOTEMPTY at least once, and
  // at this point, we are guaranteed to have removed all the kids.
  // So, we know that it won't be ENOENT or ENOTDIR or anything else.
  // try really hard to delete stuff on windows, because it has a
  // PROFOUNDLY annoying habit of not closing handles promptly when
  // files are deleted, resulting in spurious ENOTEMPTY errors.
```

For us, we are seeing the `EPERM` error, also caused by not closing handles promptly.

I have made a fix using the same strategy in the link above. Will refine and release tomorrow.

**Comment by juancarlosfarah** [comment] 2019-08-08 13:30
Running into issues with `ENOTEMPTY: directory not empty, rmdir` caused by `rimraf` when aborting duplicate space loads. This is documented here:

https://github.com/isaacs/rimraf/issues/72 

Following this example for a fix:

https://github.com/ipfs/js-ipfs/commit/26b92a19747b20cdd56a1e4c1b09f7ad1acc73e1

**Closed** 2019-08-08 18:11 UTC
Labels: bug

**Comment by juancarlosfarah** [comment] 2019-08-08 18:25
@Fer60, this has been fixed in v0.11.6 and tested in a VM running Windows 10. Please confirm that it is working on your end. Thanks again for reporting!

**Comment by Fer60** [comment] 2019-08-12 08:33
Hi Juan Carlos,

Loading is now working, thanks for that. However the problem I reported last week has returned: the window for the lab is very small and very wide, but practically unreadable. Last week you had fixed this with an arrow at the right hand bottom corner. This arrow has disappeared now. I noticed that it is possible to enlarge the window by clicking and dragging the three dots at the right hand side. But when you move back and forth in the phases you have to dot his all the time again. When you are for example in the investigation phase and go back to conceptualization and then again to investigation you need to enlarge the lab window again.
Is it not possible to make the window larger (longer)?

Cheers,

Fer



dr. Fer Coenders,
GO-GA, Department of Instructional Technology (IST)
Faculty BMS, University of Twente
https://www.golabz.eu<https://www.golabz.eu/>
https://www.utwente.nl/en/bms/ist/
Tel (+31) 053-4893081 )office); (+31) 0316-228920 (home)

**Comment by juancarlosfarah** [comment] 2019-08-13 18:23
Hi Fer. Thanks for your feedback. The functionality to change the size of the window is still there. It might be a bit hidden due to some styling issues that I will deal with before the bootcamp.

I can make the default size bigger, but I need to make sure that it doesn't make smaller apps/labs look too big.

Also, I will work on a way to "remember" the edited sizes between phase changes.
